const versions = require("./versions");
const esFeatures = require("./es-features");

const receiverHeuristics = {
  ARRAY_CONSTRUCTOR_FUNCTIONS: new Set(["Array", "from", "of", "slice", "filter", "map", "concat"]),
  ARRAY_LIKE_NAMES: new Set(["arr", "array", "list", "items", "values", "arguments"]),
  ARRAY_METHODS: new Set(["slice", "filter", "map", "concat", "from", "of"]),
  COMMON_NON_ARRAY_NAMES: new Set([
    "obj",
    "object",
    "foo",
    "bar",
    "baz",
    "data",
    "config",
    "options",
    "params",
    "props",
    "state",
    "item",
    "element",
    "node",
    "target",
    "source",
    "result",
    "response",
    "request",
    "payload",
    "model",
    "view",
    "controller",
    "service",
    "utils",
    "helpers",
    "custom",
  ]),
  COMMON_NON_SET_NAMES: new Set([
    "settings",
    "setup",
    "setter",
    "setstate",
    "setvalue",
    "setdata",
    "setitem",
    "setinterval",
    "settimeout",
    "offset",
    "dataset",
    "reset",
    "asset",
    "charset",
    "onset",
    "subset",
    "mindset",
    "closet",
    "baseset",
  ]),
  MAP_CONSTRUCTORS: new Set(["Map", "WeakMap"]),
  SET_LIKE_NAMES: new Set(["set", "sets", "seta", "setb", "set1", "set2"]),
};

module.exports = Object.assign({}, versions, esFeatures, receiverHeuristics);
