// Generated from core-js-compat 3.50.0; run pnpm scripts:generate:polyfills.
// Feature names are mapped explicitly in scripts/constants.mjs.
const coreJsPolyfillable = new Set([
  "AggregateError",
  "ArrayBufferTransfer",
  "ArrayBufferTransferToFixedLength",
  "ArrayFindLast",
  "ArrayFindLastIndex",
  "ArrayFlat",
  "ArrayFlatMap",
  "ArrayFromAsync",
  "ArrayPrototypeAt",
  "ArrayPrototypeIncludes",
  "ArrayToReversed",
  "ArrayToSorted",
  "ArrayToSpliced",
  "ArrayWith",
  "DataView",
  "DataViewGetFloat16",
  "DataViewSetFloat16",
  "ErrorCause",
  "ErrorIsError",
  "Iterator",
  "IteratorConcat",
  "JSONIsRawJSON",
  "JSONRawJSON",
  "Map",
  "MapGetOrInsert",
  "MapGetOrInsertComputed",
  "MapGroupBy",
  "MathSumPrecise",
  "ObjectEntries",
  "ObjectFromEntries",
  "ObjectGroupBy",
  "ObjectHasOwn",
  "ObjectValues",
  "Promise",
  "PromiseAllSettled",
  "PromiseAny",
  "PromiseFinally",
  "PromiseReject",
  "PromiseResolve",
  "PromiseTry",
  "PromiseWithResolvers",
  "RegExpEscape",
  "Set",
  "SetDifference",
  "SetIntersection",
  "SetIsDisjointFrom",
  "SetIsSubsetOf",
  "SetIsSupersetOf",
  "SetSymmetricDifference",
  "SetUnion",
  "StringIsWellFormed",
  "StringMatchAll",
  "StringPadEnd",
  "StringPadStart",
  "StringReplaceAll",
  "StringToWellFormed",
  "Symbol",
  "Uint8ArrayFromBase64",
  "Uint8ArrayFromHex",
  "Uint8ArraySetFromBase64",
  "Uint8ArraySetFromHex",
  "Uint8ArrayToBase64",
  "Uint8ArrayToHex",
  "WeakMap",
  "WeakSet",
  "globalThis",
]);

const POLYFILLABLE_FEATURES = coreJsPolyfillable;
const CORE_JS_POLYFILLABLE = coreJsPolyfillable;

module.exports = {
  POLYFILLABLE_FEATURES,
  CORE_JS_POLYFILLABLE,
};
