const coreJsPolyfillable = new Set([
  "ArrayBufferTransfer",
  "ArrayBufferTransferToFixedLength",
  "ArrayFindLast",
  "ArrayFindLastIndex",
  "ArrayFlat",
  "ArrayFlatMap",
  "ArrayFromAsync",
  "ArrayPrototypeAt",
  "ArrayPrototypeIncludes",
  "ArrayToReversed",
  "ArrayToSorted",
  "ArrayToSpliced",
  "ArrayWith",
  "ErrorCause",
  "ErrorIsError",
  "Map",
  "MapGroupBy",
  "ObjectEntries",
  "ObjectFromEntries",
  "ObjectGroupBy",
  "ObjectHasOwn",
  "ObjectValues",
  "Promise",
  "PromiseAllSettled",
  "PromiseAny",
  "PromiseFinally",
  "PromiseReject",
  "PromiseResolve",
  "PromiseTry",
  "PromiseWithResolvers",
  "RegExpEscape",
  "Set",
  "SetDifference",
  "SetIntersection",
  "SetIsDisjointFrom",
  "SetIsSubsetOf",
  "SetIsSupersetOf",
  "SetSymmetricDifference",
  "SetUnion",
  "StringIsWellFormed",
  "StringMatchAll",
  "StringPadEnd",
  "StringPadStart",
  "StringReplaceAll",
  "StringToWellFormed",
  "Symbol",
  "WeakMap",
  "WeakSet",
  "globalThis",
]);

const POLYFILLABLE_FEATURES = coreJsPolyfillable;
const CORE_JS_POLYFILLABLE = coreJsPolyfillable;

module.exports = {
  POLYFILLABLE_FEATURES,
  CORE_JS_POLYFILLABLE,
};
