const POLYFILLABLE_FEATURES = new Set([
  "Array.from",
  "Array.of",
  "Array.prototype.find",
  "Array.prototype.findIndex",
  "Array.prototype.includes",
  "Array.prototype.at",
  "Array.prototype.findLast",
  "Array.prototype.findLastIndex",
  "Array.prototype.toSorted",
  "Array.prototype.toReversed",
  "Array.prototype.with",
  "Array.prototype.flatMap",
  "Array.prototype.flat",
  "ArrayToSorted",
  "ArrayToReversed",
  "ArrayWith",
  "ArrayFindLast",
  "ArrayFindLastIndex",
  "ArrayAt",
  "String.prototype.includes",
  "String.prototype.startsWith",
  "String.prototype.endsWith",
  "String.prototype.repeat",
  "String.prototype.padStart",
  "String.prototype.padEnd",
  "String.prototype.trimStart",
  "String.prototype.trimEnd",
  "String.prototype.replaceAll",
  "String.prototype.matchAll",
  "String.prototype.at",
  "StringReplaceAll",
  "StringMatchAll",
  "StringAt",
  "Object.assign",
  "Object.keys",
  "Object.values",
  "Object.entries",
  "Object.fromEntries",
  "Object.hasOwn",
  "ObjectHasOwn",
  "Promise.resolve",
  "Promise.reject",
  "Promise.all",
  "Promise.race",
  "Promise.allSettled",
  "Promise.any",
  "PromiseAny",
  "PromiseAllSettled",
  "Map",
  "Set",
  "WeakMap",
  "WeakSet",
  "Symbol",
  "Symbol.iterator",
  "Symbol.asyncIterator",
  "globalThis",
  "GlobalThis",
  "Number.isNaN",
  "Number.isFinite",
  "Number.isInteger",
  "Number.isSafeInteger",
  "Number.parseFloat",
  "Number.parseInt",
  "Math.trunc",
  "Math.sign",
  "Math.cbrt",
  "Math.hypot",
  "RegExp.prototype.flags",
]);

const CORE_JS_POLYFILLABLE = new Set([
  "Array.from",
  "Array.of",
  "Array.prototype.find",
  "Array.prototype.findIndex",
  "Array.prototype.includes",
  "Array.prototype.at",
  "Array.prototype.findLast",
  "Array.prototype.findLastIndex",
  "Array.prototype.toSorted",
  "Array.prototype.toReversed",
  "Array.prototype.with",
  "ArrayToSorted",
  "ArrayToReversed",
  "ArrayWith",
  "ArrayFindLast",
  "ArrayFindLastIndex",
  "ArrayAt",
  "String.prototype.includes",
  "String.prototype.startsWith",
  "String.prototype.endsWith",
  "String.prototype.repeat",
  "String.prototype.padStart",
  "String.prototype.padEnd",
  "String.prototype.trimStart",
  "String.prototype.trimEnd",
  "String.prototype.replaceAll",
  "String.prototype.matchAll",
  "String.prototype.at",
  "StringReplaceAll",
  "StringMatchAll",
  "StringAt",
  "Object.assign",
  "Object.keys",
  "Object.values",
  "Object.entries",
  "Object.fromEntries",
  "Object.hasOwn",
  "ObjectHasOwn",
  "Promise.resolve",
  "Promise.reject",
  "Promise.all",
  "Promise.race",
  "Promise.allSettled",
  "Promise.any",
  "PromiseAny",
  "PromiseAllSettled",
  "Map",
  "Set",
  "WeakMap",
  "WeakSet",
  "Symbol",
  "Symbol.iterator",
  "Symbol.asyncIterator",
  "globalThis",
  "GlobalThis",
]);

function getPolyfillableFeatures(library) {
  if (!library) {
    return POLYFILLABLE_FEATURES;
  }

  let normalizedLibrary;
  try {
    normalizedLibrary = typeof library === 'string' ? library.toLowerCase() : String(library).toLowerCase();
  } catch {
    return POLYFILLABLE_FEATURES;
  }

  if (normalizedLibrary === "core-js") {
    return CORE_JS_POLYFILLABLE;
  }

  return POLYFILLABLE_FEATURES;
}

module.exports = {
  POLYFILLABLE_FEATURES,
  CORE_JS_POLYFILLABLE,
  getPolyfillableFeatures,
};