const TYPESCRIPT_ACCESS_MODIFIERS = ['public', 'private', 'protected', 'readonly'];

const TYPESCRIPT_STOP_CHARS = ['=', ',', ';', ')', '}', '{', '\n'];

const TYPESCRIPT_NON_NULL_ASSERTION_NEXT_CHARS = [')', ']', '.', ';', ','];

const TYPESCRIPT_STRING_QUOTES = ['"', "'", '`'];

const TYPESCRIPT_IDENTIFIER_REGEX = /[a-zA-Z_$0-9]/;

const TYPESCRIPT_WHITESPACE_REGEX = /\s/;

module.exports = {
  TYPESCRIPT_ACCESS_MODIFIERS,
  TYPESCRIPT_STOP_CHARS,
  TYPESCRIPT_NON_NULL_ASSERTION_NEXT_CHARS,
  TYPESCRIPT_STRING_QUOTES,
  TYPESCRIPT_IDENTIFIER_REGEX,
  TYPESCRIPT_WHITESPACE_REGEX,
};