const ES_GLOBAL_MIN_VERSION = {
  AggregateError: 12,
  Array: 5,
  ArrayBuffer: 6,
  Atomics: 8,
  BigInt: 11,
  BigInt64Array: 11,
  BigUint64Array: 11,
  Boolean: 5,
  DataView: 6,
  Date: 5,
  Error: 5,
  EvalError: 5,
  FinalizationRegistry: 12,
  Float16Array: 16,
  Float32Array: 6,
  Float64Array: 6,
  Function: 5,
  Infinity: 5,
  Int16Array: 6,
  Int32Array: 6,
  Int8Array: 6,
  Intl: 6,
  Iterator: 16,
  JSON: 5,
  Map: 6,
  Math: 5,
  NaN: 5,
  Number: 5,
  Object: 5,
  Promise: 6,
  Proxy: 6,
  RangeError: 5,
  ReferenceError: 5,
  Reflect: 6,
  RegExp: 5,
  Set: 6,
  SharedArrayBuffer: 8,
  String: 5,
  Symbol: 6,
  SyntaxError: 5,
  TypeError: 5,
  URIError: 5,
  Uint16Array: 6,
  Uint32Array: 6,
  Uint8Array: 6,
  Uint8ClampedArray: 6,
  WeakMap: 6,
  WeakRef: 12,
  WeakSet: 6,
  decodeURI: 5,
  decodeURIComponent: 5,
  encodeURI: 5,
  encodeURIComponent: 5,
  escape: 5,
  eval: 5,
  globalThis: 11,
  isFinite: 5,
  isNaN: 5,
  parseFloat: 5,
  parseInt: 5,
  undefined: 5,
  unescape: 5,
};

const ES_GLOBALS_SOURCE = "https://github.com/sindresorhus/globals/blob/main/globals.json";

module.exports = {
  ES_GLOBAL_MIN_VERSION,
  ES_GLOBALS_SOURCE,
};
