#!/usr/bin/env node

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { createRequire } from "module";
import {
  CHILD_FEATURES,
  SPECIAL_CASES,
  SEGMENT_REPLACEMENTS,
} from "../../constants.mjs";

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));

const coreJsModules = new Set(require("core-js-compat/modules"));
const { ES_FEATURES } = require("../../../lib/constants");

const ES_FEATURE_KEYS = new Set(Object.keys(ES_FEATURES));

function toPascalCase(segment) {
  return segment
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

function normalizeModule(mod) {
  return mod.replace(/^es\./, "").replace(/\.v\d+$/, "");
}

function convertSegment(segment) {
  return SEGMENT_REPLACEMENTS[segment] || toPascalCase(segment);
}

function moduleToFeatureName(mod) {
  const normalized = normalizeModule(mod);
  return normalized.split(".").map(convertSegment).join("");
}

function collectFeatures() {
  const features = new Set();

  coreJsModules.forEach((mod) => {
    if (!mod.startsWith("es.")) return;

    const special = SPECIAL_CASES[mod];
    if (special && ES_FEATURE_KEYS.has(special)) {
      features.add(special);
    }

    const derived = moduleToFeatureName(mod);
    if (ES_FEATURE_KEYS.has(derived)) {
      features.add(derived);
    }

    const children = CHILD_FEATURES[mod];
    if (children) {
      children
        .filter((c) => ES_FEATURE_KEYS.has(c))
        .forEach((c) => features.add(c));
    }
  });

  return [...features].sort();
}

function formatFeatureList(features) {
  return features.map((f) => `  "${f}",`).join("\n");
}

function generateFileContent(features) {
  const formatted = formatFeatureList(features);
  return `/**
 * Generated by scripts/generate/polyfills/core.mjs — do not edit manually.
 *
 * These values use es-check's internal feature names (e.g. "ArrayToSorted"),
 * not core-js module names (e.g. "es.array.to-sorted"). Core-js module names
 * cannot be used directly because es-check matches features against its own
 * ES_FEATURES keys, which follow PascalCase naming derived from acorn AST
 * detection. The generation script bridges the two naming schemes by converting
 * core-js modules to es-check feature names and intersecting with ES_FEATURES.
 */
const coreJsPolyfillable = new Set([
${formatted}
]);

const POLYFILLABLE_FEATURES = coreJsPolyfillable;
const CORE_JS_POLYFILLABLE = coreJsPolyfillable;

module.exports = {
  POLYFILLABLE_FEATURES,
  CORE_JS_POLYFILLABLE,
};
`;
}

function main() {
  const features = collectFeatures();

  if (features.length === 0) {
    process.exit(1);
  }

  const content = generateFileContent(features);
  const outputPath = join(
    __dirname,
    "../../../lib/constants/polyfillableFeatures.js",
  );

  writeFileSync(outputPath, content);
}

try {
  main();
} catch (error) {
  process.exit(1);
}
