export const ES_VERSION_TO_YEAR = {
  5: 2009,
  6: 2015,
  7: 2016,
  8: 2017,
  9: 2018,
  10: 2019,
  11: 2020,
  12: 2021,
  13: 2022,
  14: 2023,
  15: 2024,
  16: 2025,
  17: 2026,
};

export const CHROME_TO_ES = {
  46: 6,
  55: 7,
  58: 8,
  60: 9,
  75: 10,
  80: 11,
  85: 12,
  93: 13,
  97: 14,
  117: 15,
  136: 16,
  150: 17,
};

export const FEATURE_MDN_MAPPING = {
  ObjectSpread: "javascript.operators.spread.spread_in_object_literals",
  SpreadInArrays: "javascript.operators.spread.spread_in_arrays",
  OptionalChaining: "javascript.operators.optional_chaining",
  NullishCoalescing: "javascript.operators.nullish_coalescing",
  LogicalAssignment: "javascript.operators.logical_and_assignment",
  PrivateFields: "javascript.classes.private_class_fields",
  StaticInitializationBlocks: "javascript.classes.static.initialization_blocks",
  TopLevelAwait: "javascript.operators.await.top_level",
  BigInt: "javascript.builtins.BigInt",
  NumericSeparators: "javascript.grammar.numeric_separators",
};

export const CHILD_FEATURES = {
  "es.promise": ["PromiseResolve", "PromiseReject"],
  "es.array.includes": ["ArrayPrototypeIncludes"],
  "es.array.at": ["ArrayPrototypeAt"],
};

export const SPECIAL_CASES = {
  "es.global-this": "globalThis",
};

export const SEGMENT_REPLACEMENTS = {
  regexp: "RegExp",
  "array-buffer": "ArrayBuffer",
  "weak-ref": "WeakRef",
  "weak-map": "WeakMap",
  "weak-set": "WeakSet",
  "global-this": "GlobalThis",
  int8: "Int8",
  int16: "Int16",
  int32: "Int32",
  uint8: "Uint8",
  uint16: "Uint16",
  uint32: "Uint32",
  float16: "Float16",
  float32: "Float32",
  float64: "Float64",
  bigint: "BigInt",
};

export const BROWSER_SUPPORT_BROWSERS = [
  "chrome",
  "chrome_android",
  "deno",
  "edge",
  "firefox",
  "firefox_android",
  "ie",
  "nodejs",
  "opera",
  "opera_android",
  "safari",
  "safari_ios",
  "samsunginternet_android",
  "webview_android",
];

export const FEATURE_BCD_PATHS = {
  ArraySpread: "javascript.operators.spread.spread_in_arrays",
  let: "javascript.statements.let",
  const: "javascript.statements.const",
  class: "javascript.statements.class",
  extends: "javascript.classes.extends",
  import: "javascript.statements.import",
  export: "javascript.statements.export",
  ArrowFunctions: "javascript.functions.arrow_functions",
  TemplateLiterals: "javascript.grammar.template_literals",
  Destructuring: "javascript.operators.destructuring",
  DefaultParams: "javascript.functions.default_parameters",
  RestSpread: "javascript.functions.rest_parameters",
  ForOf: "javascript.statements.for_of",
  Map: "javascript.builtins.Map",
  Set: "javascript.builtins.Set",
  WeakMap: "javascript.builtins.WeakMap",
  WeakSet: "javascript.builtins.WeakSet",
  Promise: "javascript.builtins.Promise",
  PromiseResolve: "javascript.builtins.Promise.resolve",
  PromiseReject: "javascript.builtins.Promise.reject",
  Symbol: "javascript.builtins.Symbol",
  ExponentOperator: "javascript.operators.exponentiation",
  ArrayPrototypeIncludes: "javascript.builtins.Array.includes",
  AsyncAwait: "javascript.operators.async_function",
  ObjectValues: "javascript.builtins.Object.values",
  ObjectEntries: "javascript.builtins.Object.entries",
  StringPadStart: "javascript.builtins.String.padStart",
  StringPadEnd: "javascript.builtins.String.padEnd",
  ObjectSpread: "javascript.operators.spread.spread_in_object_literals",
  AsyncIteration: "javascript.statements.for_await_of",
  PromiseFinally: "javascript.builtins.Promise.finally",
  ArrayFlat: "javascript.builtins.Array.flat",
  ArrayFlatMap: "javascript.builtins.Array.flatMap",
  ObjectFromEntries: "javascript.builtins.Object.fromEntries",
  OptionalCatchBinding: "javascript.statements.try_catch.optional_catch_binding",
  BigInt: "javascript.builtins.BigInt",
  DynamicImport: "javascript.operators.import",
  OptionalChaining: "javascript.operators.optional_chaining",
  NullishCoalescing: "javascript.operators.nullish_coalescing",
  globalThis: "javascript.builtins.globalThis",
  PromiseAllSettled: "javascript.builtins.Promise.allSettled",
  StringMatchAll: "javascript.builtins.String.matchAll",
  LogicalAssignment: "javascript.operators.logical_and_assignment",
  NumericSeparators: "javascript.grammar.numeric_separators",
  StringReplaceAll: "javascript.builtins.String.replaceAll",
  PromiseAny: "javascript.builtins.Promise.any",
  WeakRef: "javascript.builtins.WeakRef",
  FinalizationRegistry: "javascript.builtins.FinalizationRegistry",
  TopLevelAwait: "javascript.operators.await.top_level",
  PrivateClassFields: "javascript.classes.private_class_fields",
  ClassStaticBlocks: "javascript.classes.static.initialization_blocks",
  ErgonomicBrandChecks: "javascript.classes.private_class_fields_in",
  ErrorCause: "javascript.builtins.Error.cause",
  ArrayPrototypeAt: "javascript.builtins.Array.at",
  ObjectHasOwn: "javascript.builtins.Object.hasOwn",
  Hashbang: "javascript.grammar.hashbang_comments",
  ArrayToReversed: "javascript.builtins.Array.toReversed",
  ArrayToSorted: "javascript.builtins.Array.toSorted",
  ArrayToSpliced: "javascript.builtins.Array.toSpliced",
  ArrayWith: "javascript.builtins.Array.with",
  ArrayFindLast: "javascript.builtins.Array.findLast",
  ArrayFindLastIndex: "javascript.builtins.Array.findLastIndex",
  StringIsWellFormed: "javascript.builtins.String.isWellFormed",
  StringToWellFormed: "javascript.builtins.String.toWellFormed",
  RegExpUnicodeSetFlag: "javascript.builtins.RegExp.unicodeSets",
  PromiseWithResolvers: "javascript.builtins.Promise.withResolvers",
  ObjectGroupBy: "javascript.builtins.Object.groupBy",
  MapGroupBy: "javascript.builtins.Map.groupBy",
  AtomicsWaitAsync: "javascript.builtins.Atomics.waitAsync",
  ArrayBufferTransfer: "javascript.builtins.ArrayBuffer.transfer",
  ArrayBufferTransferToFixedLength: "javascript.builtins.ArrayBuffer.transferToFixedLength",
  PromiseTry: "javascript.builtins.Promise.try",
  IntlDurationFormat: "javascript.builtins.Intl.DurationFormat",
  DuplicateNamedCaptureGroups:
    "javascript.regular_expressions.named_capturing_group.duplicate_named_capturing_groups",
  SetUnion: "javascript.builtins.Set.union",
  SetIntersection: "javascript.builtins.Set.intersection",
  SetDifference: "javascript.builtins.Set.difference",
  SetSymmetricDifference: "javascript.builtins.Set.symmetricDifference",
  SetIsSubsetOf: "javascript.builtins.Set.isSubsetOf",
  SetIsSupersetOf: "javascript.builtins.Set.isSupersetOf",
  SetIsDisjointFrom: "javascript.builtins.Set.isDisjointFrom",
  Float16Array: "javascript.builtins.Float16Array",
  RegExpEscape: "javascript.builtins.RegExp.escape",
  MathF16Round: "javascript.builtins.Math.f16round",
  DataViewGetFloat16: "javascript.builtins.DataView.getFloat16",
  DataViewSetFloat16: "javascript.builtins.DataView.setFloat16",
  ArrayFromAsync: "javascript.builtins.Array.fromAsync",
  ErrorIsError: "javascript.builtins.Error.isError",
  MapGetOrInsert: "javascript.builtins.Map.getOrInsert",
  MapGetOrInsertComputed: "javascript.builtins.Map.getOrInsertComputed",
  IteratorConcat: "javascript.builtins.Iterator.concat",
  JSONRawJSON: "javascript.builtins.JSON.rawJSON",
  JSONIsRawJSON: "javascript.builtins.JSON.isRawJSON",
  MathSumPrecise: "javascript.builtins.Math.sumPrecise",
  Uint8ArrayFromBase64: "javascript.builtins.Uint8Array.fromBase64",
  Uint8ArrayFromHex: "javascript.builtins.Uint8Array.fromHex",
  Uint8ArrayToBase64: "javascript.builtins.Uint8Array.toBase64",
  Uint8ArrayToHex: "javascript.builtins.Uint8Array.toHex",
  Uint8ArraySetFromBase64: "javascript.builtins.Uint8Array.setFromBase64",
  Uint8ArraySetFromHex: "javascript.builtins.Uint8Array.setFromHex",
};
